import { z } from 'zod';
export declare const createListingBaseSchema: z.ZodObject<{
    title: z.ZodString;
    description: z.ZodString;
    categoryId: z.ZodString;
    gemType: z.ZodString;
    variety: z.ZodOptional<z.ZodString>;
    originCountry: z.ZodOptional<z.ZodString>;
    originRegion: z.ZodOptional<z.ZodString>;
    caratWeight: z.ZodOptional<z.ZodNumber>;
    color: z.ZodOptional<z.ZodString>;
    clarity: z.ZodOptional<z.ZodString>;
    cut: z.ZodOptional<z.ZodString>;
    shape: z.ZodOptional<z.ZodString>;
    dimensionsMm: z.ZodOptional<z.ZodString>;
    treatment: z.ZodOptional<z.ZodString>;
    isHeatTreated: z.ZodOptional<z.ZodBoolean>;
    transparency: z.ZodOptional<z.ZodString>;
    refractiveIndex: z.ZodOptional<z.ZodNumber>;
    specificGravity: z.ZodOptional<z.ZodNumber>;
    hardness: z.ZodOptional<z.ZodNumber>;
    isCertified: z.ZodDefault<z.ZodBoolean>;
    naturalStatus: z.ZodDefault<z.ZodEnum<["NATURAL", "SYNTHETIC", "LAB_GROWN"]>>;
    mountedStatus: z.ZodDefault<z.ZodEnum<["LOOSE", "MOUNTED"]>>;
    currency: z.ZodDefault<z.ZodEnum<["LKR", "USD"]>>;
    listingType: z.ZodEnum<["FIXED_PRICE", "NEGOTIABLE", "TIMED_AUCTION", "LIVE_AUCTION"]>;
    fixedPrice: z.ZodOptional<z.ZodNumber>;
    negotiablePrice: z.ZodOptional<z.ZodNumber>;
    minAcceptableOffer: z.ZodOptional<z.ZodNumber>;
    auctionStartPrice: z.ZodOptional<z.ZodNumber>;
    reservePrice: z.ZodOptional<z.ZodNumber>;
    minBidIncrement: z.ZodOptional<z.ZodNumber>;
    auctionStartsAt: z.ZodOptional<z.ZodString>;
    auctionEndsAt: z.ZodOptional<z.ZodString>;
    autoExtend: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    title: string;
    description: string;
    categoryId: string;
    gemType: string;
    isCertified: boolean;
    naturalStatus: "NATURAL" | "SYNTHETIC" | "LAB_GROWN";
    mountedStatus: "LOOSE" | "MOUNTED";
    currency: "LKR" | "USD";
    listingType: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION";
    autoExtend: boolean;
    variety?: string | undefined;
    originCountry?: string | undefined;
    originRegion?: string | undefined;
    caratWeight?: number | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    dimensionsMm?: string | undefined;
    treatment?: string | undefined;
    isHeatTreated?: boolean | undefined;
    transparency?: string | undefined;
    refractiveIndex?: number | undefined;
    specificGravity?: number | undefined;
    hardness?: number | undefined;
    fixedPrice?: number | undefined;
    negotiablePrice?: number | undefined;
    minAcceptableOffer?: number | undefined;
    auctionStartPrice?: number | undefined;
    reservePrice?: number | undefined;
    minBidIncrement?: number | undefined;
    auctionStartsAt?: string | undefined;
    auctionEndsAt?: string | undefined;
}, {
    title: string;
    description: string;
    categoryId: string;
    gemType: string;
    listingType: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION";
    variety?: string | undefined;
    originCountry?: string | undefined;
    originRegion?: string | undefined;
    caratWeight?: number | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    dimensionsMm?: string | undefined;
    treatment?: string | undefined;
    isHeatTreated?: boolean | undefined;
    transparency?: string | undefined;
    refractiveIndex?: number | undefined;
    specificGravity?: number | undefined;
    hardness?: number | undefined;
    isCertified?: boolean | undefined;
    naturalStatus?: "NATURAL" | "SYNTHETIC" | "LAB_GROWN" | undefined;
    mountedStatus?: "LOOSE" | "MOUNTED" | undefined;
    currency?: "LKR" | "USD" | undefined;
    fixedPrice?: number | undefined;
    negotiablePrice?: number | undefined;
    minAcceptableOffer?: number | undefined;
    auctionStartPrice?: number | undefined;
    reservePrice?: number | undefined;
    minBidIncrement?: number | undefined;
    auctionStartsAt?: string | undefined;
    auctionEndsAt?: string | undefined;
    autoExtend?: boolean | undefined;
}>;
export declare const createListingSchema: z.ZodEffects<z.ZodObject<{
    title: z.ZodString;
    description: z.ZodString;
    categoryId: z.ZodString;
    gemType: z.ZodString;
    variety: z.ZodOptional<z.ZodString>;
    originCountry: z.ZodOptional<z.ZodString>;
    originRegion: z.ZodOptional<z.ZodString>;
    caratWeight: z.ZodOptional<z.ZodNumber>;
    color: z.ZodOptional<z.ZodString>;
    clarity: z.ZodOptional<z.ZodString>;
    cut: z.ZodOptional<z.ZodString>;
    shape: z.ZodOptional<z.ZodString>;
    dimensionsMm: z.ZodOptional<z.ZodString>;
    treatment: z.ZodOptional<z.ZodString>;
    isHeatTreated: z.ZodOptional<z.ZodBoolean>;
    transparency: z.ZodOptional<z.ZodString>;
    refractiveIndex: z.ZodOptional<z.ZodNumber>;
    specificGravity: z.ZodOptional<z.ZodNumber>;
    hardness: z.ZodOptional<z.ZodNumber>;
    isCertified: z.ZodDefault<z.ZodBoolean>;
    naturalStatus: z.ZodDefault<z.ZodEnum<["NATURAL", "SYNTHETIC", "LAB_GROWN"]>>;
    mountedStatus: z.ZodDefault<z.ZodEnum<["LOOSE", "MOUNTED"]>>;
    currency: z.ZodDefault<z.ZodEnum<["LKR", "USD"]>>;
    listingType: z.ZodEnum<["FIXED_PRICE", "NEGOTIABLE", "TIMED_AUCTION", "LIVE_AUCTION"]>;
    fixedPrice: z.ZodOptional<z.ZodNumber>;
    negotiablePrice: z.ZodOptional<z.ZodNumber>;
    minAcceptableOffer: z.ZodOptional<z.ZodNumber>;
    auctionStartPrice: z.ZodOptional<z.ZodNumber>;
    reservePrice: z.ZodOptional<z.ZodNumber>;
    minBidIncrement: z.ZodOptional<z.ZodNumber>;
    auctionStartsAt: z.ZodOptional<z.ZodString>;
    auctionEndsAt: z.ZodOptional<z.ZodString>;
    autoExtend: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    title: string;
    description: string;
    categoryId: string;
    gemType: string;
    isCertified: boolean;
    naturalStatus: "NATURAL" | "SYNTHETIC" | "LAB_GROWN";
    mountedStatus: "LOOSE" | "MOUNTED";
    currency: "LKR" | "USD";
    listingType: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION";
    autoExtend: boolean;
    variety?: string | undefined;
    originCountry?: string | undefined;
    originRegion?: string | undefined;
    caratWeight?: number | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    dimensionsMm?: string | undefined;
    treatment?: string | undefined;
    isHeatTreated?: boolean | undefined;
    transparency?: string | undefined;
    refractiveIndex?: number | undefined;
    specificGravity?: number | undefined;
    hardness?: number | undefined;
    fixedPrice?: number | undefined;
    negotiablePrice?: number | undefined;
    minAcceptableOffer?: number | undefined;
    auctionStartPrice?: number | undefined;
    reservePrice?: number | undefined;
    minBidIncrement?: number | undefined;
    auctionStartsAt?: string | undefined;
    auctionEndsAt?: string | undefined;
}, {
    title: string;
    description: string;
    categoryId: string;
    gemType: string;
    listingType: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION";
    variety?: string | undefined;
    originCountry?: string | undefined;
    originRegion?: string | undefined;
    caratWeight?: number | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    dimensionsMm?: string | undefined;
    treatment?: string | undefined;
    isHeatTreated?: boolean | undefined;
    transparency?: string | undefined;
    refractiveIndex?: number | undefined;
    specificGravity?: number | undefined;
    hardness?: number | undefined;
    isCertified?: boolean | undefined;
    naturalStatus?: "NATURAL" | "SYNTHETIC" | "LAB_GROWN" | undefined;
    mountedStatus?: "LOOSE" | "MOUNTED" | undefined;
    currency?: "LKR" | "USD" | undefined;
    fixedPrice?: number | undefined;
    negotiablePrice?: number | undefined;
    minAcceptableOffer?: number | undefined;
    auctionStartPrice?: number | undefined;
    reservePrice?: number | undefined;
    minBidIncrement?: number | undefined;
    auctionStartsAt?: string | undefined;
    auctionEndsAt?: string | undefined;
    autoExtend?: boolean | undefined;
}>, {
    title: string;
    description: string;
    categoryId: string;
    gemType: string;
    isCertified: boolean;
    naturalStatus: "NATURAL" | "SYNTHETIC" | "LAB_GROWN";
    mountedStatus: "LOOSE" | "MOUNTED";
    currency: "LKR" | "USD";
    listingType: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION";
    autoExtend: boolean;
    variety?: string | undefined;
    originCountry?: string | undefined;
    originRegion?: string | undefined;
    caratWeight?: number | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    dimensionsMm?: string | undefined;
    treatment?: string | undefined;
    isHeatTreated?: boolean | undefined;
    transparency?: string | undefined;
    refractiveIndex?: number | undefined;
    specificGravity?: number | undefined;
    hardness?: number | undefined;
    fixedPrice?: number | undefined;
    negotiablePrice?: number | undefined;
    minAcceptableOffer?: number | undefined;
    auctionStartPrice?: number | undefined;
    reservePrice?: number | undefined;
    minBidIncrement?: number | undefined;
    auctionStartsAt?: string | undefined;
    auctionEndsAt?: string | undefined;
}, {
    title: string;
    description: string;
    categoryId: string;
    gemType: string;
    listingType: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION";
    variety?: string | undefined;
    originCountry?: string | undefined;
    originRegion?: string | undefined;
    caratWeight?: number | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    dimensionsMm?: string | undefined;
    treatment?: string | undefined;
    isHeatTreated?: boolean | undefined;
    transparency?: string | undefined;
    refractiveIndex?: number | undefined;
    specificGravity?: number | undefined;
    hardness?: number | undefined;
    isCertified?: boolean | undefined;
    naturalStatus?: "NATURAL" | "SYNTHETIC" | "LAB_GROWN" | undefined;
    mountedStatus?: "LOOSE" | "MOUNTED" | undefined;
    currency?: "LKR" | "USD" | undefined;
    fixedPrice?: number | undefined;
    negotiablePrice?: number | undefined;
    minAcceptableOffer?: number | undefined;
    auctionStartPrice?: number | undefined;
    reservePrice?: number | undefined;
    minBidIncrement?: number | undefined;
    auctionStartsAt?: string | undefined;
    auctionEndsAt?: string | undefined;
    autoExtend?: boolean | undefined;
}>;
export type CreateListingInput = z.infer<typeof createListingSchema>;
export declare const updateListingSchema: z.ZodObject<{
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    categoryId: z.ZodOptional<z.ZodString>;
    gemType: z.ZodOptional<z.ZodString>;
    variety: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    originCountry: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    originRegion: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    caratWeight: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    color: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    clarity: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    cut: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    shape: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    dimensionsMm: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    treatment: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    isHeatTreated: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
    transparency: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    refractiveIndex: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    specificGravity: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    hardness: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    isCertified: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    naturalStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<["NATURAL", "SYNTHETIC", "LAB_GROWN"]>>>;
    mountedStatus: z.ZodOptional<z.ZodDefault<z.ZodEnum<["LOOSE", "MOUNTED"]>>>;
    currency: z.ZodOptional<z.ZodDefault<z.ZodEnum<["LKR", "USD"]>>>;
    listingType: z.ZodOptional<z.ZodEnum<["FIXED_PRICE", "NEGOTIABLE", "TIMED_AUCTION", "LIVE_AUCTION"]>>;
    fixedPrice: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    negotiablePrice: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    minAcceptableOffer: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    auctionStartPrice: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    reservePrice: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    minBidIncrement: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    auctionStartsAt: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    auctionEndsAt: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    autoExtend: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
}, "strip", z.ZodTypeAny, {
    title?: string | undefined;
    description?: string | undefined;
    categoryId?: string | undefined;
    gemType?: string | undefined;
    variety?: string | undefined;
    originCountry?: string | undefined;
    originRegion?: string | undefined;
    caratWeight?: number | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    dimensionsMm?: string | undefined;
    treatment?: string | undefined;
    isHeatTreated?: boolean | undefined;
    transparency?: string | undefined;
    refractiveIndex?: number | undefined;
    specificGravity?: number | undefined;
    hardness?: number | undefined;
    isCertified?: boolean | undefined;
    naturalStatus?: "NATURAL" | "SYNTHETIC" | "LAB_GROWN" | undefined;
    mountedStatus?: "LOOSE" | "MOUNTED" | undefined;
    currency?: "LKR" | "USD" | undefined;
    listingType?: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION" | undefined;
    fixedPrice?: number | undefined;
    negotiablePrice?: number | undefined;
    minAcceptableOffer?: number | undefined;
    auctionStartPrice?: number | undefined;
    reservePrice?: number | undefined;
    minBidIncrement?: number | undefined;
    auctionStartsAt?: string | undefined;
    auctionEndsAt?: string | undefined;
    autoExtend?: boolean | undefined;
}, {
    title?: string | undefined;
    description?: string | undefined;
    categoryId?: string | undefined;
    gemType?: string | undefined;
    variety?: string | undefined;
    originCountry?: string | undefined;
    originRegion?: string | undefined;
    caratWeight?: number | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    dimensionsMm?: string | undefined;
    treatment?: string | undefined;
    isHeatTreated?: boolean | undefined;
    transparency?: string | undefined;
    refractiveIndex?: number | undefined;
    specificGravity?: number | undefined;
    hardness?: number | undefined;
    isCertified?: boolean | undefined;
    naturalStatus?: "NATURAL" | "SYNTHETIC" | "LAB_GROWN" | undefined;
    mountedStatus?: "LOOSE" | "MOUNTED" | undefined;
    currency?: "LKR" | "USD" | undefined;
    listingType?: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION" | undefined;
    fixedPrice?: number | undefined;
    negotiablePrice?: number | undefined;
    minAcceptableOffer?: number | undefined;
    auctionStartPrice?: number | undefined;
    reservePrice?: number | undefined;
    minBidIncrement?: number | undefined;
    auctionStartsAt?: string | undefined;
    auctionEndsAt?: string | undefined;
    autoExtend?: boolean | undefined;
}>;
export type UpdateListingInput = z.infer<typeof updateListingSchema>;
export declare const listingIdSchema: z.ZodObject<{
    id: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
}, {
    id: string;
}>;
//# sourceMappingURL=listing.d.ts.map