import { z } from 'zod';
export declare const searchListingsSchema: z.ZodObject<{
    q: z.ZodOptional<z.ZodString>;
    gemType: z.ZodOptional<z.ZodString>;
    variety: z.ZodOptional<z.ZodString>;
    categoryId: z.ZodOptional<z.ZodString>;
    color: z.ZodOptional<z.ZodString>;
    clarity: z.ZodOptional<z.ZodString>;
    cut: z.ZodOptional<z.ZodString>;
    shape: z.ZodOptional<z.ZodString>;
    caratMin: z.ZodOptional<z.ZodNumber>;
    caratMax: z.ZodOptional<z.ZodNumber>;
    priceMin: z.ZodOptional<z.ZodNumber>;
    priceMax: z.ZodOptional<z.ZodNumber>;
    currency: z.ZodOptional<z.ZodEnum<["LKR", "USD"]>>;
    treatment: z.ZodOptional<z.ZodString>;
    certifiedOnly: z.ZodOptional<z.ZodBoolean>;
    labName: z.ZodOptional<z.ZodString>;
    originCountry: z.ZodOptional<z.ZodString>;
    naturalStatus: z.ZodOptional<z.ZodEnum<["NATURAL", "SYNTHETIC", "LAB_GROWN"]>>;
    listingType: z.ZodOptional<z.ZodEnum<["FIXED_PRICE", "NEGOTIABLE", "TIMED_AUCTION", "LIVE_AUCTION"]>>;
    verifiedSellersOnly: z.ZodOptional<z.ZodBoolean>;
    isFeatured: z.ZodOptional<z.ZodBoolean>;
    page: z.ZodDefault<z.ZodNumber>;
    pageSize: z.ZodDefault<z.ZodNumber>;
    sortBy: z.ZodDefault<z.ZodEnum<["newest", "price_asc", "price_desc", "ending_soon", "most_viewed", "carat_desc", "carat_asc"]>>;
}, "strip", z.ZodTypeAny, {
    page: number;
    pageSize: number;
    sortBy: "newest" | "price_asc" | "price_desc" | "ending_soon" | "most_viewed" | "carat_desc" | "carat_asc";
    categoryId?: string | undefined;
    gemType?: string | undefined;
    variety?: string | undefined;
    originCountry?: string | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    treatment?: string | undefined;
    naturalStatus?: "NATURAL" | "SYNTHETIC" | "LAB_GROWN" | undefined;
    currency?: "LKR" | "USD" | undefined;
    listingType?: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION" | undefined;
    q?: string | undefined;
    caratMin?: number | undefined;
    caratMax?: number | undefined;
    priceMin?: number | undefined;
    priceMax?: number | undefined;
    certifiedOnly?: boolean | undefined;
    labName?: string | undefined;
    verifiedSellersOnly?: boolean | undefined;
    isFeatured?: boolean | undefined;
}, {
    categoryId?: string | undefined;
    gemType?: string | undefined;
    variety?: string | undefined;
    originCountry?: string | undefined;
    color?: string | undefined;
    clarity?: string | undefined;
    cut?: string | undefined;
    shape?: string | undefined;
    treatment?: string | undefined;
    naturalStatus?: "NATURAL" | "SYNTHETIC" | "LAB_GROWN" | undefined;
    currency?: "LKR" | "USD" | undefined;
    listingType?: "FIXED_PRICE" | "NEGOTIABLE" | "TIMED_AUCTION" | "LIVE_AUCTION" | undefined;
    q?: string | undefined;
    caratMin?: number | undefined;
    caratMax?: number | undefined;
    priceMin?: number | undefined;
    priceMax?: number | undefined;
    certifiedOnly?: boolean | undefined;
    labName?: string | undefined;
    verifiedSellersOnly?: boolean | undefined;
    isFeatured?: boolean | undefined;
    page?: number | undefined;
    pageSize?: number | undefined;
    sortBy?: "newest" | "price_asc" | "price_desc" | "ending_soon" | "most_viewed" | "carat_desc" | "carat_asc" | undefined;
}>;
export type SearchListingsInput = z.infer<typeof searchListingsSchema>;
export declare const paginationSchema: z.ZodObject<{
    page: z.ZodDefault<z.ZodNumber>;
    pageSize: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    page: number;
    pageSize: number;
}, {
    page?: number | undefined;
    pageSize?: number | undefined;
}>;
export type PaginationInput = z.infer<typeof paginationSchema>;
//# sourceMappingURL=search.d.ts.map